# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Company.create(name: 'ASTRA AB')
Company.create(name: 'AGILENT TECHNOLOGIES INC')
Company.create(name: 'ALCOA INC')
Company.create(name: 'ALTANA A G')
Company.create(name: 'ADMIRALTY BANCORP INC')
Company.create(name: 'ACCESS ANYTIME BANCORP')
Company.create(name: 'ARCADIA FINANCIAL LTD')
Company.create(name: 'AUSTRALIA ACQUISITION CORP')
Company.create(name: 'ALLIANCE ATLANTIS COMMS INC')
Company.create(name: 'ASSET ACCEPTANCE CAPITAL CORP')
Company.create(name: 'ACE CASH EXPRESS INC')
Company.create(name: 'ADVISORSHARES TRUST')
Company.create(name: 'ADVANTAGE BANCORP INC')
Company.create(name: 'AMERICAN GOVERNMENT INC PORT INC')
Company.create(name: 'ALL AMERICAN FOOD GROUP INC')
Company.create(name: 'ANGLO AMERICAN GOLD INVT LTD')
Company.create(name: 'AMBASSADOR APARTMENTS INC')
Company.create(name: 'AQUA ALLIANCE INC')
Company.create(name: 'AIRTRAN HOLDINGS INC')
Company.create(name: 'ALABAMA AIRCRAFT INDUSTRIES INC')
Company.create(name: 'AAIPHARMA INC')
Company.create(name: 'iShares MSCI AC Asia Information Tech (AAIT)')
Company.create(name: 'AMERALIA INC')
Company.create(name: 'AAMES FINANCIAL CORP')
Company.create(name: 'ATLANTIC AMERICAN CORP')
Company.create(name: 'AARONS INC')
Company.create(name: 'ABIGAIL ADAMS NATL BANCORP INC')
Company.create(name: 'AAON INC')
Company.create(name: 'AMWAY ASIA PACIFIC LTD')
Company.create(name: 'ADVANCE AUTO PARTS INC')
Company.create(name: 'APPLE INC')
Company.create(name: 'ADVANCED AERODYNAMICS STRUC INC')
Company.create(name: 'ALL AMERICAN SPORTPARK INC')
Company.create(name: 'ALL AMERICAN TERM TRUST INC')
Company.create(name: 'AMERICAN ASSETS TRUST INC')
Company.create(name: 'ANALYSIS & TECHNOLOGY INC')
Company.create(name: 'ADVANCED ANALOGIC TCHNLGS INC')
Company.create(name: 'AAVID THERMAL TECHNOLOGIES INC')
Company.create(name: 'ALMADEN MINERALS LTD')
Company.create(name: 'ANGLO AMERICAN P L C')
Company.create(name: 'AVATEX CORP')
Company.create(name: 'ADVANTAGE OIL & GAS LTD')
Company.create(name: 'ATLAS AIR WORLDWIDE HOLDINGS INC')
Company.create(name: 'ISHARES TRUST')
Company.create(name: 'CANNON EXPRESS INC')
Company.create(name: 'ALLIANCEBERNSTEIN HOLDING L P')
Company.create(name: 'ABACAN RESOURCE CORP NEW')
Company.create(name: 'SAFETY COMPONENTS INTL INC')
Company.create(name: 'AMERICAN BANCSHARES INC FL')
Company.create(name: 'ADVANCED BATTERY TECHNOLS INC')
Company.create(name: 'ABAXIS INC')
Company.create(name: 'A B B LTD')
Company.create(name: 'A B B AB')
Company.create(name: 'ABINGTON BANCORP INC PA')
Company.create(name: 'ABINGTON BANCORP INC NEW')
Company.create(name: 'AMERISOURCEBERGEN CORP')
Company.create(name: 'AMERIS BANCORP')
Company.create(name: 'A B C DISPENSING TECHS INC')
Company.create(name: 'CAMBIUM LEARNING GROUP INC')
Company.create(name: 'ALLIANCE BANCORP INC')
Company.create(name: 'AMERICAN BUILDINGS CO NEW')
Company.create(name: 'ADVISORY BOARD CO')
Company.create(name: 'A B C N A C O INC')
Company.create(name: 'CLAYMORE E T F TRUST 2')
Company.create(name: 'ANCHOR BANCORP WISCONSIN INC')
Company.create(name: 'AUTOBOND ACCEPTANCE CORP')
Company.create(name: 'ABACUS DIRECT CORP')
Company.create(name: 'AIRBORNE INC')
Company.create(name: 'AMERICAN BUSINESS FINL SRVCS INC')
Company.create(name: 'ARKANSAS BEST CORP DEL')
Company.create(name: 'GROUPE A B SA')
Company.create(name: 'ASBURY AUTOMOTIVE GROUP INC')
Company.create(name: 'ABGENIX INC')
Company.create(name: 'AMERICAN BANK NT HGRHCS INC DEL')
Company.create(name: 'ABITIBIBOWATER INC')
Company.create(name: 'AMERICAN BANKERS INS GROUP INC')
Company.create(name: 'APPLIED BIOSYSTEMS INC DEL')
Company.create(name: 'ABRAXIS BIOSCIENCE INC NEW')
Company.create(name: 'ARCA BIOPHARMA INC')
Company.create(name: 'ABATIX CORP')
Company.create(name: 'ADELPHIA BUSINESS SOLUTIONS INC')
Company.create(name: 'AMBAC FINANCIAL GROUP INC')
Company.create(name: 'AMERICAN BILTRITE INC')
Company.create(name: 'ABLE ENERGY INC')
Company.create(name: 'A B M INDUSTRIES INC')
Company.create(name: 'AMERICAN BIO MEDICA CORP')
Company.create(name: 'ABIOMED INC')
Company.create(name: 'AMERICAN BANKNOTE CORP')
Company.create(name: 'A B N AMRO HOLDING N V')
Company.create(name: 'AMERICAN BANCORP OF NJ INC')
Company.create(name: 'AMEGY BANCORPORATION INC')
Company.create(name: 'ABOVENET COMMUNICATIONS INC')
Company.create(name: 'AMERICAN BUSINESS PRODS INC GA')
Company.create(name: 'AMBASSADOR BANK OF THE CMMWLTH')
Company.create(name: 'ACCENTIA BIOPHARMACEUTICALS INC')
Company.create(name: 'ATLANTIC PREMIUM BRANDS LTD')
Company.create(name: 'ARBOR REALTY TRUST INC')
Company.create(name: 'AMERICAN CRAFT BREWING INTL')
Company.create(name: 'A B R INFORMATION SERVICES INC')
Company.create(name: 'ABLE LABORATORIES INC')
stocksymbol.create(name: 'A.1', trading_name: 'A', company_id: 1)
stocksymbol.create(name: 'AAB', trading_name: 'AAB', company_id: 1)
stocksymbol.create(name: 'A', trading_name: 'A', company_id: 2)
stocksymbol.create(name: 'AA', trading_name: 'AA', company_id: 3)
stocksymbol.create(name: 'AAA', trading_name: 'AAA', company_id: 4)
stocksymbol.create(name: 'AAAB', trading_name: 'AAAB', company_id: 5)
stocksymbol.create(name: 'AABC', trading_name: 'AABC', company_id: 6)
stocksymbol.create(name: 'AAC.1', trading_name: 'AAC', company_id: 7)
stocksymbol.create(name: 'AAC.2', trading_name: 'AAC', company_id: 8)
stocksymbol.create(name: 'AACB', trading_name: 'AACB', company_id: 9)
stocksymbol.create(name: 'AACC', trading_name: 'AACC', company_id: 10)
stocksymbol.create(name: 'AACE', trading_name: 'AACE', company_id: 11)
stocksymbol.create(name: 'AADR', trading_name: 'AADR', company_id: 12)
stocksymbol.create(name: 'ACCU', trading_name: 'ACCU', company_id: 12)
stocksymbol.create(name: 'AGLS', trading_name: 'AGLS', company_id: 12)
stocksymbol.create(name: 'DBIZ', trading_name: 'DBIZ', company_id: 12)
stocksymbol.create(name: 'DENT', trading_name: 'DENT', company_id: 12)
stocksymbol.create(name: 'FWDB', trading_name: 'FWDB', company_id: 12)
stocksymbol.create(name: 'FWDD', trading_name: 'FWDD', company_id: 12)
stocksymbol.create(name: 'FWDI', trading_name: 'FWDI', company_id: 12)
stocksymbol.create(name: 'GIVE', trading_name: 'GIVE', company_id: 12)
stocksymbol.create(name: 'GTAA', trading_name: 'GTAA', company_id: 12)
stocksymbol.create(name: 'HDGE', trading_name: 'HDGE', company_id: 12)
stocksymbol.create(name: 'HYLD', trading_name: 'HYLD', company_id: 12)
stocksymbol.create(name: 'MATH', trading_name: 'MATH', company_id: 12)
stocksymbol.create(name: 'QEH', trading_name: 'QEH', company_id: 12)
stocksymbol.create(name: 'EPRO', trading_name: 'EPRO', company_id: 12)
stocksymbol.create(name: 'SSAM', trading_name: 'SSAM', company_id: 12)
stocksymbol.create(name: 'TTFS', trading_name: 'TTFS', company_id: 12)
stocksymbol.create(name: 'VEGA', trading_name: 'VEGA', company_id: 12)
stocksymbol.create(name: 'AADV', trading_name: 'AADV', company_id: 13)
stocksymbol.create(name: 'AAF', trading_name: 'AAF', company_id: 14)
stocksymbol.create(name: 'AAFG', trading_name: 'AAFG', company_id: 15)
stocksymbol.create(name: 'AAGIY', trading_name: 'AAGIY', company_id: 16)
stocksymbol.create(name: 'AAH', trading_name: 'AAH', company_id: 17)
stocksymbol.create(name: 'AAI.1', trading_name: 'AAI', company_id: 18)
stocksymbol.create(name: 'AAI', trading_name: 'AAI', company_id: 19)
stocksymbol.create(name: 'AAII', trading_name: 'AAII', company_id: 20)
stocksymbol.create(name: 'AAIIE', trading_name: 'AAIIE', company_id: 21)
stocksymbol.create(name: 'AAIT', trading_name: 'AAIT', company_id: 22)
stocksymbol.create(name: 'AALA', trading_name: 'AALA', company_id: 23)
stocksymbol.create(name: 'AAM', trading_name: 'AAM', company_id: 24)
stocksymbol.create(name: 'AAME', trading_name: 'AAME', company_id: 25)
stocksymbol.create(name: 'AAN.1', trading_name: 'AAN', company_id: 26)
stocksymbol.create(name: 'AAN', trading_name: 'AAN', company_id: 26)
stocksymbol.create(name: 'AANB', trading_name: 'AANB', company_id: 27)
stocksymbol.create(name: 'AAON', trading_name: 'AAON', company_id: 28)
stocksymbol.create(name: 'AAP.1', trading_name: 'AAP', company_id: 29)
stocksymbol.create(name: 'AAP', trading_name: 'AAP', company_id: 30)
stocksymbol.create(name: 'AAPL', trading_name: 'AAPL', company_id: 31)
stocksymbol.create(name: 'AASI', trading_name: 'AASI', company_id: 32)
stocksymbol.create(name: 'AASP', trading_name: 'AASP', company_id: 33)
stocksymbol.create(name: 'AAT.1', trading_name: 'AAT', company_id: 34)
stocksymbol.create(name: 'AAT', trading_name: 'AAT', company_id: 35)
stocksymbol.create(name: 'AATI.1', trading_name: 'AATI', company_id: 36)
stocksymbol.create(name: 'AATI', trading_name: 'AATI', company_id: 37)
stocksymbol.create(name: 'AATT', trading_name: 'AATT', company_id: 38)
stocksymbol.create(name: 'AAU', trading_name: 'AAU', company_id: 39)
stocksymbol.create(name: 'AAUK', trading_name: 'AAUK', company_id: 40)
stocksymbol.create(name: 'AAV.1', trading_name: 'AAV', company_id: 41)
stocksymbol.create(name: 'AAV', trading_name: 'AAV', company_id: 42)
stocksymbol.create(name: 'AAWW', trading_name: 'AAWW', company_id: 43)
stocksymbol.create(name: 'CGO.1', trading_name: 'CGO', company_id: 43)
stocksymbol.create(name: 'AAXJ', trading_name: 'AAXJ', company_id: 44)
stocksymbol.create(name: 'ACWI', trading_name: 'ACWI', company_id: 44)
stocksymbol.create(name: 'ACWX', trading_name: 'ACWX', company_id: 44)
stocksymbol.create(name: 'AGG', trading_name: 'AGG', company_id: 44)
stocksymbol.create(name: 'AGZ', trading_name: 'AGZ', company_id: 44)
stocksymbol.create(name: 'AIA', trading_name: 'AIA', company_id: 44)
stocksymbol.create(name: 'ALT', trading_name: 'ALT', company_id: 44)
stocksymbol.create(name: 'AMPS', trading_name: 'AMPS', company_id: 44)
stocksymbol.create(name: 'AOA', trading_name: 'AOA', company_id: 44)
stocksymbol.create(name: 'AOK', trading_name: 'AOK', company_id: 44)
stocksymbol.create(name: 'AOM', trading_name: 'AOM', company_id: 44)
stocksymbol.create(name: 'AOR', trading_name: 'AOR', company_id: 44)
stocksymbol.create(name: 'AXDI', trading_name: 'AXDI', company_id: 44)
stocksymbol.create(name: 'AXEN', trading_name: 'AXEN', company_id: 44)
stocksymbol.create(name: 'AXHE', trading_name: 'AXHE', company_id: 44)
stocksymbol.create(name: 'AXID', trading_name: 'AXID', company_id: 44)
stocksymbol.create(name: 'AXIT', trading_name: 'AXIT', company_id: 44)
stocksymbol.create(name: 'AXMT', trading_name: 'AXMT', company_id: 44)
stocksymbol.create(name: 'AXSL', trading_name: 'AXSL', company_id: 44)
stocksymbol.create(name: 'AXTE', trading_name: 'AXTE', company_id: 44)
stocksymbol.create(name: 'AXUT', trading_name: 'AXUT', company_id: 44)
stocksymbol.create(name: 'CFT', trading_name: 'CFT', company_id: 44)
stocksymbol.create(name: 'CIU', trading_name: 'CIU', company_id: 44)
stocksymbol.create(name: 'CLY', trading_name: 'CLY', company_id: 44)
stocksymbol.create(name: 'CMBS', trading_name: 'CMBS', company_id: 44)
stocksymbol.create(name: 'CMF', trading_name: 'CMF', company_id: 44)
stocksymbol.create(name: 'CSJ', trading_name: 'CSJ', company_id: 44)
stocksymbol.create(name: 'DSI', trading_name: 'DSI', company_id: 44)
stocksymbol.create(name: 'DVY', trading_name: 'DVY', company_id: 44)
stocksymbol.create(name: 'ECNS', trading_name: 'ECNS', company_id: 44)
stocksymbol.create(name: 'EEM', trading_name: 'EEM', company_id: 44)
stocksymbol.create(name: 'EFA', trading_name: 'EFA', company_id: 44)
stocksymbol.create(name: 'EFAV', trading_name: 'EFAV', company_id: 44)
stocksymbol.create(name: 'EFG', trading_name: 'EFG', company_id: 44)
stocksymbol.create(name: 'EFV', trading_name: 'EFV', company_id: 44)
stocksymbol.create(name: 'EIDO', trading_name: 'EIDO', company_id: 44)
stocksymbol.create(name: 'EIRL', trading_name: 'EIRL', company_id: 44)
stock_symbol_1 = StockSymbol.find(2)
stock_symbol_2 = StockSymbol.find(50)
user_guest_1 = User.create!(name: 'guest', email: '')
portfolio_1 = Portfolio.create(user: user_guest_1, name: 'Crazy Eights')
portfolio_1.open_positions.new(stock_symbol: stock_symbol_1, quantity: 100, cost: 113.16, date_acquired: Date.new(2009,9, 1))
portfolio_1.open_positions.new(stock_symbol: stock_symbol_2, quantity: 250, cost:   3.16, date_acquired: Date.new(2010,2,15))
portfolio_1.save!
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20090812, open_price: 113.16, close_price: 114.24, high_price: 115.01, low_price: 112.11, trade_volume: 1341)
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20090912, open_price: 115.16, close_price: 116.24, high_price: 116.24, low_price: 114.11, trade_volume: 1141)
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20091012, open_price: 111.16, close_price: 114.24, high_price: 115.01, low_price: 112.11, trade_volume:  941)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100116, open_price:   3.16, close_price:   4.24, high_price:   5.01, low_price:   2.11, trade_volume: 1776)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100216, open_price:   5.16, close_price:   6.24, high_price:   5.01, low_price:   4.11, trade_volume: 1576)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100316, open_price:   3.16, close_price:   5.24, high_price:   6.01, low_price:   3.11, trade_volume: 1376)
