c=Company.create(name: 'ASTRA AB')
c.stock_symbols.create(name: 'A.1', trading_name: 'A')
c.stock_symbols.create(name: 'AAB', trading_name: 'AAB')
c=Company.create(name: 'AGILENT TECHNOLOGIES INC')
c.stock_symbols.create(name: 'A', trading_name: 'A')
c=Company.create(name: 'ALCOA INC')
c.stock_symbols.create(name: 'AA', trading_name: 'AA')
c=Company.create(name: 'ALTANA A G')
c.stock_symbols.create(name: 'AAA', trading_name: 'AAA')
c=Company.create(name: 'ADMIRALTY BANCORP INC')
c.stock_symbols.create(name: 'AAAB', trading_name: 'AAAB')
c=Company.create(name: 'ACCESS ANYTIME BANCORP')
c.stock_symbols.create(name: 'AABC', trading_name: 'AABC')
c=Company.create(name: 'ARCADIA FINANCIAL LTD')
c.stock_symbols.create(name: 'AAC.1', trading_name: 'AAC')
c=Company.create(name: 'AUSTRALIA ACQUISITION CORP')
c.stock_symbols.create(name: 'AAC.2', trading_name: 'AAC')
c=Company.create(name: 'ALLIANCE ATLANTIS COMMS INC')
c.stock_symbols.create(name: 'AACB', trading_name: 'AACB')
c=Company.create(name: 'ASSET ACCEPTANCE CAPITAL CORP')
c.stock_symbols.create(name: 'AACC', trading_name: 'AACC')
c=Company.create(name: 'ACE CASH EXPRESS INC')
c.stock_symbols.create(name: 'AACE', trading_name: 'AACE')
c=Company.create(name: 'ADVISORSHARES TRUST')
c.stock_symbols.create(name: 'AADR', trading_name: 'AADR')
c.stock_symbols.create(name: 'ACCU', trading_name: 'ACCU')
c.stock_symbols.create(name: 'AGLS', trading_name: 'AGLS')
c.stock_symbols.create(name: 'DBIZ', trading_name: 'DBIZ')
c.stock_symbols.create(name: 'DENT', trading_name: 'DENT')
c.stock_symbols.create(name: 'FWDB', trading_name: 'FWDB')
c.stock_symbols.create(name: 'FWDD', trading_name: 'FWDD')
c.stock_symbols.create(name: 'FWDI', trading_name: 'FWDI')
c.stock_symbols.create(name: 'GIVE', trading_name: 'GIVE')
c.stock_symbols.create(name: 'GTAA', trading_name: 'GTAA')
c.stock_symbols.create(name: 'HDGE', trading_name: 'HDGE')
c.stock_symbols.create(name: 'HYLD', trading_name: 'HYLD')
c.stock_symbols.create(name: 'MATH', trading_name: 'MATH')
c.stock_symbols.create(name: 'QEH', trading_name: 'QEH')
c.stock_symbols.create(name: 'EPRO', trading_name: 'EPRO')
c.stock_symbols.create(name: 'SSAM', trading_name: 'SSAM')
c.stock_symbols.create(name: 'TTFS', trading_name: 'TTFS')
c.stock_symbols.create(name: 'VEGA', trading_name: 'VEGA')
c=Company.create(name: 'ADVANTAGE BANCORP INC')
c.stock_symbols.create(name: 'AADV', trading_name: 'AADV')
c=Company.create(name: 'AMERICAN GOVERNMENT INC PORT INC')
c.stock_symbols.create(name: 'AAF', trading_name: 'AAF')
c=Company.create(name: 'ALL AMERICAN FOOD GROUP INC')
c.stock_symbols.create(name: 'AAFG', trading_name: 'AAFG')
c=Company.create(name: 'ANGLO AMERICAN GOLD INVT LTD')
c.stock_symbols.create(name: 'AAGIY', trading_name: 'AAGIY')
c=Company.create(name: 'AMBASSADOR APARTMENTS INC')
c.stock_symbols.create(name: 'AAH', trading_name: 'AAH')
c=Company.create(name: 'AQUA ALLIANCE INC')
c.stock_symbols.create(name: 'AAI.1', trading_name: 'AAI')
c=Company.create(name: 'AIRTRAN HOLDINGS INC')
c.stock_symbols.create(name: 'AAI', trading_name: 'AAI')
c=Company.create(name: 'ALABAMA AIRCRAFT INDUSTRIES INC')
c.stock_symbols.create(name: 'AAII', trading_name: 'AAII')
c=Company.create(name: 'AAIPHARMA INC')
c.stock_symbols.create(name: 'AAIIE', trading_name: 'AAIIE')
c=Company.create(name: 'ISHARES MSCI AC ASIA INFORMATION TECH (AAIT)')
c.stock_symbols.create(name: 'AAIT', trading_name: 'AAIT')
c=Company.create(name: 'AMERALIA INC')
c.stock_symbols.create(name: 'AALA', trading_name: 'AALA')
c=Company.create(name: 'AAMES FINANCIAL CORP')
c.stock_symbols.create(name: 'AAM', trading_name: 'AAM')
c=Company.create(name: 'ATLANTIC AMERICAN CORP')
c.stock_symbols.create(name: 'AAME', trading_name: 'AAME')
c=Company.create(name: 'AARONS INC')
c.stock_symbols.create(name: 'AAN.1', trading_name: 'AAN')
c.stock_symbols.create(name: 'AAN', trading_name: 'AAN')
c=Company.create(name: 'ABIGAIL ADAMS NATL BANCORP INC')
c.stock_symbols.create(name: 'AANB', trading_name: 'AANB')
c=Company.create(name: 'AAON INC')
c.stock_symbols.create(name: 'AAON', trading_name: 'AAON')
c=Company.create(name: 'AMWAY ASIA PACIFIC LTD')
c.stock_symbols.create(name: 'AAP.1', trading_name: 'AAP')
c=Company.create(name: 'ADVANCE AUTO PARTS INC')
c.stock_symbols.create(name: 'AAP', trading_name: 'AAP')
c=Company.create(name: 'APPLE INC')
c.stock_symbols.create(name: 'AAPL', trading_name: 'AAPL')
c=Company.create(name: 'ADVANCED AERODYNAMICS STRUC INC')
c.stock_symbols.create(name: 'AASI', trading_name: 'AASI')
c=Company.create(name: 'ALL AMERICAN SPORTPARK INC')
c.stock_symbols.create(name: 'AASP', trading_name: 'AASP')
c=Company.create(name: 'ALL AMERICAN TERM TRUST INC')
c.stock_symbols.create(name: 'AAT.1', trading_name: 'AAT')
c=Company.create(name: 'AMERICAN ASSETS TRUST INC')
c.stock_symbols.create(name: 'AAT', trading_name: 'AAT')
c=Company.create(name: 'ANALYSIS & TECHNOLOGY INC')
c.stock_symbols.create(name: 'AATI.1', trading_name: 'AATI')
c=Company.create(name: 'ADVANCED ANALOGIC TCHNLGS INC')
c.stock_symbols.create(name: 'AATI', trading_name: 'AATI')
c=Company.create(name: 'AAVID THERMAL TECHNOLOGIES INC')
c.stock_symbols.create(name: 'AATT', trading_name: 'AATT')
c=Company.create(name: 'ALMADEN MINERALS LTD')
c.stock_symbols.create(name: 'AAU', trading_name: 'AAU')
c=Company.create(name: 'ANGLO AMERICAN P L C')
c.stock_symbols.create(name: 'AAUK', trading_name: 'AAUK')
c=Company.create(name: 'AVATEX CORP')
c.stock_symbols.create(name: 'AAV.1', trading_name: 'AAV')
c=Company.create(name: 'ADVANTAGE OIL & GAS LTD')
c.stock_symbols.create(name: 'AAV', trading_name: 'AAV')
c=Company.create(name: 'ATLAS AIR WORLDWIDE HOLDINGS INC')
c.stock_symbols.create(name: 'AAWW', trading_name: 'AAWW')
c.stock_symbols.create(name: 'CGO.1', trading_name: 'CGO')
c=Company.create(name: 'ISHARES TRUST')
c.stock_symbols.create(name: 'AAXJ', trading_name: 'AAXJ')
c.stock_symbols.create(name: 'ACWI', trading_name: 'ACWI')
c.stock_symbols.create(name: 'ACWX', trading_name: 'ACWX')
c.stock_symbols.create(name: 'AGG', trading_name: 'AGG')
c.stock_symbols.create(name: 'AGZ', trading_name: 'AGZ')
c.stock_symbols.create(name: 'AIA', trading_name: 'AIA')
c.stock_symbols.create(name: 'ALT', trading_name: 'ALT')
c.stock_symbols.create(name: 'AMPS', trading_name: 'AMPS')
c.stock_symbols.create(name: 'AOA', trading_name: 'AOA')
c.stock_symbols.create(name: 'AOK', trading_name: 'AOK')
c.stock_symbols.create(name: 'AOM', trading_name: 'AOM')
c.stock_symbols.create(name: 'AOR', trading_name: 'AOR')
c.stock_symbols.create(name: 'AXDI', trading_name: 'AXDI')
c.stock_symbols.create(name: 'AXEN', trading_name: 'AXEN')
c.stock_symbols.create(name: 'AXHE', trading_name: 'AXHE')
c.stock_symbols.create(name: 'AXID', trading_name: 'AXID')
c.stock_symbols.create(name: 'AXIT', trading_name: 'AXIT')
c.stock_symbols.create(name: 'AXMT', trading_name: 'AXMT')
c.stock_symbols.create(name: 'AXSL', trading_name: 'AXSL')
c.stock_symbols.create(name: 'AXTE', trading_name: 'AXTE')
c.stock_symbols.create(name: 'AXUT', trading_name: 'AXUT')
c.stock_symbols.create(name: 'CFT', trading_name: 'CFT')
c.stock_symbols.create(name: 'CIU', trading_name: 'CIU')
c.stock_symbols.create(name: 'CLY', trading_name: 'CLY')
c.stock_symbols.create(name: 'CMBS', trading_name: 'CMBS')
c.stock_symbols.create(name: 'CMF', trading_name: 'CMF')
c.stock_symbols.create(name: 'CSJ', trading_name: 'CSJ')
c.stock_symbols.create(name: 'DSI', trading_name: 'DSI')
c.stock_symbols.create(name: 'DVY', trading_name: 'DVY')
c.stock_symbols.create(name: 'ECNS', trading_name: 'ECNS')
c.stock_symbols.create(name: 'EEM', trading_name: 'EEM')
c.stock_symbols.create(name: 'EFA', trading_name: 'EFA')
c.stock_symbols.create(name: 'EFAV', trading_name: 'EFAV')
c.stock_symbols.create(name: 'EFG', trading_name: 'EFG')
c.stock_symbols.create(name: 'EFV', trading_name: 'EFV')
c.stock_symbols.create(name: 'EIDO', trading_name: 'EIDO')
c.stock_symbols.create(name: 'EIRL', trading_name: 'EIRL')
c.stock_symbols.create(name: 'EMB', trading_name: 'EMB')
c.stock_symbols.create(name: 'ENGN', trading_name: 'ENGN')
c.stock_symbols.create(name: 'ENZL', trading_name: 'ENZL')
c.stock_symbols.create(name: 'EPHE', trading_name: 'EPHE')
c.stock_symbols.create(name: 'EPOL', trading_name: 'EPOL')
c.stock_symbols.create(name: 'EPU', trading_name: 'EPU')
c.stock_symbols.create(name: 'ERUS', trading_name: 'ERUS')
c.stock_symbols.create(name: 'EWHS', trading_name: 'EWHS')
c.stock_symbols.create(name: 'EWSS', trading_name: 'EWSS')
c.stock_symbols.create(name: 'EWZS', trading_name: 'EWZS')
c.stock_symbols.create(name: 'EXI', trading_name: 'EXI')
c.stock_symbols.create(name: 'FCHI', trading_name: 'FCHI')
c.stock_symbols.create(name: 'FLOT', trading_name: 'FLOT')
c.stock_symbols.create(name: 'FNIO', trading_name: 'FNIO')
c.stock_symbols.create(name: 'FTY', trading_name: 'FTY')
c.stock_symbols.create(name: 'FXI', trading_name: 'FXI')
c.stock_symbols.create(name: 'GBF', trading_name: 'GBF')
c.stock_symbols.create(name: 'GOVT', trading_name: 'GOVT')
c.stock_symbols.create(name: 'GTIP', trading_name: 'GTIP')
c.stock_symbols.create(name: 'GVI', trading_name: 'GVI')
c.stock_symbols.create(name: 'HDV', trading_name: 'HDV')
c.stock_symbols.create(name: 'HYG', trading_name: 'HYG')
c.stock_symbols.create(name: 'IAI', trading_name: 'IAI')
c.stock_symbols.create(name: 'IAK', trading_name: 'IAK')
c.stock_symbols.create(name: 'IAT', trading_name: 'IAT')
c.stock_symbols.create(name: 'IAU', trading_name: 'IAU')
c.stock_symbols.create(name: 'IBB', trading_name: 'IBB')
c.stock_symbols.create(name: 'ICF', trading_name: 'ICF')
c.stock_symbols.create(name: 'ICLN', trading_name: 'ICLN')
c.stock_symbols.create(name: 'IDU', trading_name: 'IDU')
c.stock_symbols.create(name: 'IDV', trading_name: 'IDV')
c.stock_symbols.create(name: 'IEF', trading_name: 'IEF')
c.stock_symbols.create(name: 'IEFA', trading_name: 'IEFA')
c.stock_symbols.create(name: 'IEI', trading_name: 'IEI')
c.stock_symbols.create(name: 'IEO', trading_name: 'IEO')
c.stock_symbols.create(name: 'IEV', trading_name: 'IEV')
c.stock_symbols.create(name: 'IEZ', trading_name: 'IEZ')
c.stock_symbols.create(name: 'IFAS', trading_name: 'IFAS')
c.stock_symbols.create(name: 'IFEU', trading_name: 'IFEU')
c.stock_symbols.create(name: 'IFGL', trading_name: 'IFGL')
c.stock_symbols.create(name: 'IFNA', trading_name: 'IFNA')
c.stock_symbols.create(name: 'IEUS', trading_name: 'IEUS')
c.stock_symbols.create(name: 'IGE', trading_name: 'IGE')
c.stock_symbols.create(name: 'IGF', trading_name: 'IGF')
c.stock_symbols.create(name: 'IGM', trading_name: 'IGM')
c.stock_symbols.create(name: 'IGN', trading_name: 'IGN')
c.stock_symbols.create(name: 'IGOV', trading_name: 'IGOV')
c.stock_symbols.create(name: 'IGV', trading_name: 'IGV')
c.stock_symbols.create(name: 'IHE', trading_name: 'IHE')
c.stock_symbols.create(name: 'IHF', trading_name: 'IHF')
c.stock_symbols.create(name: 'IHI', trading_name: 'IHI')
c.stock_symbols.create(name: 'IJH', trading_name: 'IJH')
c.stock_symbols.create(name: 'IJJ', trading_name: 'IJJ')
c.stock_symbols.create(name: 'IJK', trading_name: 'IJK')
c.stock_symbols.create(name: 'IJR', trading_name: 'IJR')
c.stock_symbols.create(name: 'IJS', trading_name: 'IJS')
c.stock_symbols.create(name: 'IJT', trading_name: 'IJT')
c.stock_symbols.create(name: 'IKC', trading_name: 'IKC')
c.stock_symbols.create(name: 'ILF', trading_name: 'ILF')
c.stock_symbols.create(name: 'ILTB', trading_name: 'ILTB')
c.stock_symbols.create(name: 'IOO', trading_name: 'IOO')
c.stock_symbols.create(name: 'IPFF', trading_name: 'IPFF')
c.stock_symbols.create(name: 'ISHG', trading_name: 'ISHG')
c.stock_symbols.create(name: 'ISTB', trading_name: 'ISTB')
c.stock_symbols.create(name: 'ITA', trading_name: 'ITA')
c.stock_symbols.create(name: 'ITB', trading_name: 'ITB')
c.stock_symbols.create(name: 'JPXN', trading_name: 'JPXN')
c.stock_symbols.create(name: 'ITIP', trading_name: 'ITIP')
c.stock_symbols.create(name: 'ITOT', trading_name: 'ITOT')
c.stock_symbols.create(name: 'IVE', trading_name: 'IVE')
c.stock_symbols.create(name: 'IVV', trading_name: 'IVV')
c.stock_symbols.create(name: 'IVW', trading_name: 'IVW')
c.stock_symbols.create(name: 'IWB', trading_name: 'IWB')
c.stock_symbols.create(name: 'IWC', trading_name: 'IWC')
c.stock_symbols.create(name: 'IWD', trading_name: 'IWD')
c.stock_symbols.create(name: 'IWF', trading_name: 'IWF')
c.stock_symbols.create(name: 'IWL', trading_name: 'IWL')
c.stock_symbols.create(name: 'IWM', trading_name: 'IWM')
c.stock_symbols.create(name: 'IWN', trading_name: 'IWN')
c.stock_symbols.create(name: 'IWO', trading_name: 'IWO')
c.stock_symbols.create(name: 'IWP', trading_name: 'IWP')
c.stock_symbols.create(name: 'IWR', trading_name: 'IWR')
c.stock_symbols.create(name: 'IWS', trading_name: 'IWS')
c.stock_symbols.create(name: 'IWV', trading_name: 'IWV')
c.stock_symbols.create(name: 'IWW', trading_name: 'IWW')
c.stock_symbols.create(name: 'IWX', trading_name: 'IWX')
c.stock_symbols.create(name: 'IWY', trading_name: 'IWY')
c.stock_symbols.create(name: 'IWZ', trading_name: 'IWZ')
c.stock_symbols.create(name: 'IXC', trading_name: 'IXC')
c.stock_symbols.create(name: 'IXG', trading_name: 'IXG')
c.stock_symbols.create(name: 'IXJ', trading_name: 'IXJ')
c.stock_symbols.create(name: 'IXN', trading_name: 'IXN')
c.stock_symbols.create(name: 'IXP', trading_name: 'IXP')
c.stock_symbols.create(name: 'IXUS', trading_name: 'IXUS')
c.stock_symbols.create(name: 'IYC', trading_name: 'IYC')
c.stock_symbols.create(name: 'IYD', trading_name: 'IYD')
c.stock_symbols.create(name: 'IYE', trading_name: 'IYE')
c.stock_symbols.create(name: 'IYF', trading_name: 'IYF')
c.stock_symbols.create(name: 'IYG', trading_name: 'IYG')
c.stock_symbols.create(name: 'IYH', trading_name: 'IYH')
c.stock_symbols.create(name: 'IYJ', trading_name: 'IYJ')
c.stock_symbols.create(name: 'IYK', trading_name: 'IYK')
c.stock_symbols.create(name: 'IYM', trading_name: 'IYM')
c.stock_symbols.create(name: 'IYR', trading_name: 'IYR')
c.stock_symbols.create(name: 'IYT', trading_name: 'IYT')
c.stock_symbols.create(name: 'IYV', trading_name: 'IYV')
c.stock_symbols.create(name: 'IYW', trading_name: 'IYW')
c.stock_symbols.create(name: 'IYY', trading_name: 'IYY')
c.stock_symbols.create(name: 'IYZ', trading_name: 'IYZ')
c.stock_symbols.create(name: 'JKD', trading_name: 'JKD')
c.stock_symbols.create(name: 'JKE', trading_name: 'JKE')
c.stock_symbols.create(name: 'JKF', trading_name: 'JKF')
c.stock_symbols.create(name: 'JKG', trading_name: 'JKG')
c.stock_symbols.create(name: 'JKH', trading_name: 'JKH')
c.stock_symbols.create(name: 'JKI', trading_name: 'JKI')
c.stock_symbols.create(name: 'JKJ', trading_name: 'JKJ')
c.stock_symbols.create(name: 'JKK', trading_name: 'JKK')
c.stock_symbols.create(name: 'JKL', trading_name: 'JKL')
c.stock_symbols.create(name: 'JXI', trading_name: 'JXI')
c.stock_symbols.create(name: 'KLD', trading_name: 'KLD')
c.stock_symbols.create(name: 'KXI', trading_name: 'KXI')
c.stock_symbols.create(name: 'LQD', trading_name: 'LQD')
c.stock_symbols.create(name: 'MBB', trading_name: 'MBB')
c.stock_symbols.create(name: 'MCHI', trading_name: 'MCHI')
c.stock_symbols.create(name: 'MONY', trading_name: 'MONY')
c.stock_symbols.create(name: 'MUAA', trading_name: 'MUAA')
c.stock_symbols.create(name: 'MUAB', trading_name: 'MUAB')
c.stock_symbols.create(name: 'MUAC', trading_name: 'MUAC')
c.stock_symbols.create(name: 'IBMD', trading_name: 'IBMD')
c.stock_symbols.create(name: 'IBME', trading_name: 'IBME')
c.stock_symbols.create(name: 'IBMF', trading_name: 'IBMF')
c.stock_symbols.create(name: 'MUB', trading_name: 'MUB')
c.stock_symbols.create(name: 'MXI', trading_name: 'MXI')
c.stock_symbols.create(name: 'NUCL', trading_name: 'NUCL')
c.stock_symbols.create(name: 'NY', trading_name: 'NY')
c.stock_symbols.create(name: 'NYC', trading_name: 'NYC')
c.stock_symbols.create(name: 'NYF', trading_name: 'NYF')
c.stock_symbols.create(name: 'OEF', trading_name: 'OEF')
c.stock_symbols.create(name: 'PFF', trading_name: 'PFF')
c.stock_symbols.create(name: 'QLTA', trading_name: 'QLTA')
c.stock_symbols.create(name: 'REM', trading_name: 'REM')
c.stock_symbols.create(name: 'REZ', trading_name: 'REZ')
c.stock_symbols.create(name: 'RTL', trading_name: 'RTL')
c.stock_symbols.create(name: 'RXI', trading_name: 'RXI')
c.stock_symbols.create(name: 'SCZ', trading_name: 'SCZ')
c.stock_symbols.create(name: 'SHV', trading_name: 'SHV')
c.stock_symbols.create(name: 'SHY', trading_name: 'SHY')
c.stock_symbols.create(name: 'SLV', trading_name: 'SLV')
c.stock_symbols.create(name: 'SOXX', trading_name: 'SOXX')
c.stock_symbols.create(name: 'STIP', trading_name: 'STIP')
c.stock_symbols.create(name: 'SUB', trading_name: 'SUB')
c.stock_symbols.create(name: 'TGR', trading_name: 'TGR')
c.stock_symbols.create(name: 'TIP', trading_name: 'TIP')
c.stock_symbols.create(name: 'TLH', trading_name: 'TLH')
c.stock_symbols.create(name: 'TLT', trading_name: 'TLT')
c.stock_symbols.create(name: 'TOK', trading_name: 'TOK')
c.stock_symbols.create(name: 'TZD', trading_name: 'TZD')
c.stock_symbols.create(name: 'TZE', trading_name: 'TZE')
c.stock_symbols.create(name: 'TZG', trading_name: 'TZG')
c.stock_symbols.create(name: 'TZI', trading_name: 'TZI')
c.stock_symbols.create(name: 'TZL', trading_name: 'TZL')
c.stock_symbols.create(name: 'TZO', trading_name: 'TZO')
c.stock_symbols.create(name: 'TZV', trading_name: 'TZV')
c.stock_symbols.create(name: 'TZW', trading_name: 'TZW')
c.stock_symbols.create(name: 'TZY', trading_name: 'TZY')
c.stock_symbols.create(name: 'USMV', trading_name: 'USMV')
c.stock_symbols.create(name: 'WOOD', trading_name: 'WOOD')
c.stock_symbols.create(name: 'WPS', trading_name: 'WPS')
c=Company.create(name: 'CANNON EXPRESS INC')
c.stock_symbols.create(name: 'AB.1', trading_name: 'AB')
c=Company.create(name: 'ALLIANCEBERNSTEIN HOLDING L P')
c.stock_symbols.create(name: 'AB', trading_name: 'AB')
c=Company.create(name: 'ABACAN RESOURCE CORP NEW')
c.stock_symbols.create(name: 'ABACF', trading_name: 'ABACF')
c=Company.create(name: 'SAFETY COMPONENTS INTL INC')
c.stock_symbols.create(name: 'ABAGE', trading_name: 'ABAGE')
c=Company.create(name: 'AMERICAN BANCSHARES INC FL')
c.stock_symbols.create(name: 'ABAN', trading_name: 'ABAN')
c=Company.create(name: 'ADVANCED BATTERY TECHNOLS INC')
c.stock_symbols.create(name: 'ABAT', trading_name: 'ABAT')
c=Company.create(name: 'ABAXIS INC')
c.stock_symbols.create(name: 'ABAX', trading_name: 'ABAX')
c=Company.create(name: 'A B B LTD')
c.stock_symbols.create(name: 'ABB', trading_name: 'ABB')
c=Company.create(name: 'A B B AB')
c.stock_symbols.create(name: 'ABBBY', trading_name: 'ABBBY')
c=Company.create(name: 'ABINGTON BANCORP INC PA')
c.stock_symbols.create(name: 'ABBC', trading_name: 'ABBC')
c=Company.create(name: 'ABINGTON BANCORP INC NEW')
c.stock_symbols.create(name: 'ABBK', trading_name: 'ABBK')
c=Company.create(name: 'AMERISOURCEBERGEN CORP')
c.stock_symbols.create(name: 'ABC', trading_name: 'ABC')
c=Company.create(name: 'AMERIS BANCORP')
c.stock_symbols.create(name: 'ABCB', trading_name: 'ABCB')
c=Company.create(name: 'A B C DISPENSING TECHS INC')
c.stock_symbols.create(name: 'ABCC', trading_name: 'ABCC')
c=Company.create(name: 'CAMBIUM LEARNING GROUP INC')
c.stock_symbols.create(name: 'ABCD', trading_name: 'ABCD')
c=Company.create(name: 'ALLIANCE BANCORP INC')
c.stock_symbols.create(name: 'ABCL', trading_name: 'ABCL')
c=Company.create(name: 'AMERICAN BUILDINGS CO NEW')
c.stock_symbols.create(name: 'ABCO.1', trading_name: 'ABCO')
c=Company.create(name: 'ADVISORY BOARD CO')
c.stock_symbols.create(name: 'ABCO', trading_name: 'ABCO')
c=Company.create(name: 'A B C N A C O INC')
c.stock_symbols.create(name: 'ABCR', trading_name: 'ABCR')
c=Company.create(name: 'CLAYMORE E T F TRUST 2')
c.stock_symbols.create(name: 'ABCS', trading_name: 'ABCS')
c.stock_symbols.create(name: 'CGW', trading_name: 'CGW')
c.stock_symbols.create(name: 'CQQQ', trading_name: 'CQQQ')
c.stock_symbols.create(name: 'CRO', trading_name: 'CRO')
c.stock_symbols.create(name: 'CUT', trading_name: 'CUT')
c.stock_symbols.create(name: 'EEN', trading_name: 'EEN')
c.stock_symbols.create(name: 'EEW', trading_name: 'EEW')
c.stock_symbols.create(name: 'ENY', trading_name: 'ENY')
c.stock_symbols.create(name: 'EXB', trading_name: 'EXB')
c.stock_symbols.create(name: 'FAA', trading_name: 'FAA')
c.stock_symbols.create(name: 'FRN', trading_name: 'FRN')
c.stock_symbols.create(name: 'HAO', trading_name: 'HAO')
c.stock_symbols.create(name: 'HGI', trading_name: 'HGI')
c.stock_symbols.create(name: 'JNR', trading_name: 'JNR')
c.stock_symbols.create(name: 'RMB', trading_name: 'RMB')
c.stock_symbols.create(name: 'ROB', trading_name: 'ROB')
c.stock_symbols.create(name: 'SEA.3', trading_name: 'SEA')
c.stock_symbols.create(name: 'SEA', trading_name: 'SEA')
c.stock_symbols.create(name: 'TAN', trading_name: 'TAN')
c.stock_symbols.create(name: 'TAO', trading_name: 'TAO')
c=Company.create(name: 'ANCHOR BANCORP WISCONSIN INC')
c.stock_symbols.create(name: 'ABCW.1', trading_name: 'ABCW')
c=Company.create(name: 'AUTOBOND ACCEPTANCE CORP')
c.stock_symbols.create(name: 'ABD.1', trading_name: 'ABD')
c=Company.create(name: 'ABACUS DIRECT CORP')
c.stock_symbols.create(name: 'ABDR', trading_name: 'ABDR')
c=Company.create(name: 'AIRBORNE INC')
c.stock_symbols.create(name: 'ABF', trading_name: 'ABF')
c=Company.create(name: 'AMERICAN BUSINESS FINL SRVCS INC')
c.stock_symbols.create(name: 'ABFIQ', trading_name: 'ABFIQ')
c=Company.create(name: 'ARKANSAS BEST CORP DEL')
c.stock_symbols.create(name: 'ARCB', trading_name: 'ARCB')
c=Company.create(name: 'GROUPE A B SA')
c.stock_symbols.create(name: 'ABG.1', trading_name: 'ABG')
c=Company.create(name: 'ASBURY AUTOMOTIVE GROUP INC')
c.stock_symbols.create(name: 'ABG', trading_name: 'ABG')
c=Company.create(name: 'ABGENIX INC')
c.stock_symbols.create(name: 'ABGX', trading_name: 'ABGX')
c=Company.create(name: 'AMERICAN BANK NT HGRHCS INC DEL')
c.stock_symbols.create(name: 'ABH.1', trading_name: 'ABH')
c=Company.create(name: 'ABITIBIBOWATER INC')
c.stock_symbols.create(name: 'ABH', trading_name: 'ABH')
c=Company.create(name: 'AMERICAN BANKERS INS GROUP INC')
c.stock_symbols.create(name: 'ABI.1', trading_name: 'ABI')
c=Company.create(name: 'APPLIED BIOSYSTEMS INC DEL')
c.stock_symbols.create(name: 'ABI', trading_name: 'ABI')
c=Company.create(name: 'ABRAXIS BIOSCIENCE INC NEW')
c.stock_symbols.create(name: 'ABII', trading_name: 'ABII')
c=Company.create(name: 'ARCA BIOPHARMA INC')
c.stock_symbols.create(name: 'ABIO', trading_name: 'ABIO')
c=Company.create(name: 'ABATIX CORP')
c.stock_symbols.create(name: 'ABIX', trading_name: 'ABIX')
c=Company.create(name: 'ADELPHIA BUSINESS SOLUTIONS INC')
c.stock_symbols.create(name: 'ABIZQ', trading_name: 'ABIZQ')
c=Company.create(name: 'AMBAC FINANCIAL GROUP INC')
c.stock_symbols.create(name: 'ABK', trading_name: 'ABK')
c=Company.create(name: 'AMERICAN BILTRITE INC')
c.stock_symbols.create(name: 'ABL', trading_name: 'ABL')
c=Company.create(name: 'ABLE ENERGY INC')
c.stock_symbols.create(name: 'ABLE', trading_name: 'ABLE')
c=Company.create(name: 'A B M INDUSTRIES INC')
c.stock_symbols.create(name: 'ABM', trading_name: 'ABM')
c=Company.create(name: 'AMERICAN BIO MEDICA CORP')
c.stock_symbols.create(name: 'ABMC', trading_name: 'ABMC')
c=Company.create(name: 'ABIOMED INC')
c.stock_symbols.create(name: 'ABMD', trading_name: 'ABMD')
c=Company.create(name: 'AMERICAN BANKNOTE CORP')
c.stock_symbols.create(name: 'ABN.1', trading_name: 'ABN')
c=Company.create(name: 'A B N AMRO HOLDING N V')
c.stock_symbols.create(name: 'ABN', trading_name: 'ABN')
c=Company.create(name: 'AMERICAN BANCORP OF NJ INC')
c.stock_symbols.create(name: 'ABNJ', trading_name: 'ABNJ')
c=Company.create(name: 'AMEGY BANCORPORATION INC')
c.stock_symbols.create(name: 'ABNK', trading_name: 'ABNK')
c=Company.create(name: 'ABOVENET COMMUNICATIONS INC')
c.stock_symbols.create(name: 'ABOV', trading_name: 'ABOV')
c=Company.create(name: 'AMERICAN BUSINESS PRODS INC GA')
c.stock_symbols.create(name: 'ABP', trading_name: 'ABP')
c=Company.create(name: 'AMBASSADOR BANK OF THE CMMWLTH')
c.stock_symbols.create(name: 'ABPA', trading_name: 'ABPA')
c=Company.create(name: 'ACCENTIA BIOPHARMACEUTICALS INC')
c.stock_symbols.create(name: 'ABPI', trading_name: 'ABPI')
c=Company.create(name: 'ATLANTIC PREMIUM BRANDS LTD')
c.stock_symbols.create(name: 'ABR.1', trading_name: 'ABR')
c=Company.create(name: 'ARBOR REALTY TRUST INC')
c.stock_symbols.create(name: 'ABR', trading_name: 'ABR')
c=Company.create(name: 'AMERICAN CRAFT BREWING INTL')
c.stock_symbols.create(name: 'ABREF', trading_name: 'ABREF')
c=Company.create(name: 'A B R INFORMATION SERVICES INC')
c.stock_symbols.create(name: 'ABRX', trading_name: 'ABRX')
c=Company.create(name: 'ABLE LABORATORIES INC')
c.stock_symbols.create(name: 'ABRXQ', trading_name: 'ABRXQ')
stock_symbol_1 = StockSymbol.order(:name).offset( 2).limit(1).first
stock_symbol_2 = StockSymbol.order(:name).offset(42).limit(1).first
user_guest_1 = User.create!(name: 'guest', email: '')
portfolio_1 = Portfolio.create(user: user_guest_1, name: 'Crazy Eights')
portfolio_1.positions.new(stock_symbol: stock_symbol_1, quantity: 100, cost: 113.16, date_acquired: Date.new(2009,9, 1))
portfolio_1.positions.new(stock_symbol: stock_symbol_2, quantity: 250, cost:   3.16, date_acquired: Date.new(2010,2,15))
portfolio_1.save!
Trade.create(stock_symbol: stock_symbol_1, trade_date: '2009-08-12', trade_price: 114.24, price_change:  1.12)
Trade.create(stock_symbol: stock_symbol_1, trade_date: '2009-09-12', trade_price: 116.24, price_change:  2.00)
Trade.create(stock_symbol: stock_symbol_1, trade_date: '2009-10-12', trade_price: 114.24, price_change: -2.00)
Trade.create(stock_symbol: stock_symbol_2, trade_date: '2010-01-16', trade_price:   4.24, price_change:  0.23)
Trade.create(stock_symbol: stock_symbol_2, trade_date: '2010-02-16', trade_price:   6.36, price_change:  2.12)
Trade.create(stock_symbol: stock_symbol_2, trade_date: '2010-03-16', trade_price:   5.24, price_change: -1.12)
