# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Company.create(name: 'ASTRA AB')
Company.create(name: 'AGILENT TECHNOLOGIES INC')
Company.create(name: 'ALCOA INC')
Company.create(name: 'ALTANA A G')
Company.create(name: 'ADMIRALTY BANCORP INC')
Company.create(name: 'ACCESS ANYTIME BANCORP')
Company.create(name: 'ARCADIA FINANCIAL LTD')
Company.create(name: 'AUSTRALIA ACQUISITION CORP')
Company.create(name: 'ALLIANCE ATLANTIS COMMS INC')
Company.create(name: 'ASSET ACCEPTANCE CAPITAL CORP')
Company.create(name: 'ACE CASH EXPRESS INC')
Company.create(name: 'ADVISORSHARES TRUST')
Company.create(name: 'ADVANTAGE BANCORP INC')
Company.create(name: 'AMERICAN GOVERNMENT INC PORT INC')
Company.create(name: 'ALL AMERICAN FOOD GROUP INC')
Company.create(name: 'ANGLO AMERICAN GOLD INVT LTD')
Company.create(name: 'AMBASSADOR APARTMENTS INC')
Company.create(name: 'AQUA ALLIANCE INC')
Company.create(name: 'AIRTRAN HOLDINGS INC')
Company.create(name: 'ALABAMA AIRCRAFT INDUSTRIES INC')
Company.create(name: 'AAIPHARMA INC')
Company.create(name: 'iShares MSCI AC Asia Information Tech (AAIT)')
Company.create(name: 'AMERALIA INC')
Company.create(name: 'AAMES FINANCIAL CORP')
Company.create(name: 'ATLANTIC AMERICAN CORP')
Company.create(name: 'AARONS INC')
Company.create(name: 'ABIGAIL ADAMS NATL BANCORP INC')
Company.create(name: 'AAON INC')
Company.create(name: 'AMWAY ASIA PACIFIC LTD')
Company.create(name: 'ADVANCE AUTO PARTS INC')
Company.create(name: 'APPLE INC')
Company.create(name: 'ADVANCED AERODYNAMICS STRUC INC')
Company.create(name: 'ALL AMERICAN SPORTPARK INC')
Company.create(name: 'ALL AMERICAN TERM TRUST INC')
Company.create(name: 'AMERICAN ASSETS TRUST INC')
Company.create(name: 'ANALYSIS & TECHNOLOGY INC')
Company.create(name: 'ADVANCED ANALOGIC TCHNLGS INC')
Company.create(name: 'AAVID THERMAL TECHNOLOGIES INC')
Company.create(name: 'ALMADEN MINERALS LTD')
Company.create(name: 'ANGLO AMERICAN P L C')
Company.create(name: 'AVATEX CORP')
Company.create(name: 'ADVANTAGE OIL & GAS LTD')
Company.create(name: 'ATLAS AIR WORLDWIDE HOLDINGS INC')
Company.create(name: 'ISHARES TRUST')
Company.create(name: 'CANNON EXPRESS INC')
Company.create(name: 'ALLIANCEBERNSTEIN HOLDING L P')
Company.create(name: 'ABACAN RESOURCE CORP NEW')
Company.create(name: 'SAFETY COMPONENTS INTL INC')
Company.create(name: 'AMERICAN BANCSHARES INC FL')
Company.create(name: 'ADVANCED BATTERY TECHNOLS INC')
Company.create(name: 'ABAXIS INC')
Company.create(name: 'A B B LTD')
Company.create(name: 'A B B AB')
Company.create(name: 'ABINGTON BANCORP INC PA')
Company.create(name: 'ABINGTON BANCORP INC NEW')
Company.create(name: 'AMERISOURCEBERGEN CORP')
Company.create(name: 'AMERIS BANCORP')
Company.create(name: 'A B C DISPENSING TECHS INC')
Company.create(name: 'CAMBIUM LEARNING GROUP INC')
Company.create(name: 'ALLIANCE BANCORP INC')
Company.create(name: 'AMERICAN BUILDINGS CO NEW')
Company.create(name: 'ADVISORY BOARD CO')
Company.create(name: 'A B C N A C O INC')
Company.create(name: 'CLAYMORE E T F TRUST 2')
Company.create(name: 'ANCHOR BANCORP WISCONSIN INC')
Company.create(name: 'AUTOBOND ACCEPTANCE CORP')
Company.create(name: 'ABACUS DIRECT CORP')
Company.create(name: 'AIRBORNE INC')
Company.create(name: 'AMERICAN BUSINESS FINL SRVCS INC')
Company.create(name: 'ARKANSAS BEST CORP DEL')
Company.create(name: 'GROUPE A B SA')
Company.create(name: 'ASBURY AUTOMOTIVE GROUP INC')
Company.create(name: 'ABGENIX INC')
Company.create(name: 'AMERICAN BANK NT HGRHCS INC DEL')
Company.create(name: 'ABITIBIBOWATER INC')
Company.create(name: 'AMERICAN BANKERS INS GROUP INC')
Company.create(name: 'APPLIED BIOSYSTEMS INC DEL')
Company.create(name: 'ABRAXIS BIOSCIENCE INC NEW')
Company.create(name: 'ARCA BIOPHARMA INC')
Company.create(name: 'ABATIX CORP')
Company.create(name: 'ADELPHIA BUSINESS SOLUTIONS INC')
Company.create(name: 'AMBAC FINANCIAL GROUP INC')
Company.create(name: 'AMERICAN BILTRITE INC')
Company.create(name: 'ABLE ENERGY INC')
Company.create(name: 'A B M INDUSTRIES INC')
Company.create(name: 'AMERICAN BIO MEDICA CORP')
Company.create(name: 'ABIOMED INC')
Company.create(name: 'AMERICAN BANKNOTE CORP')
Company.create(name: 'A B N AMRO HOLDING N V')
Company.create(name: 'AMERICAN BANCORP OF NJ INC')
Company.create(name: 'AMEGY BANCORPORATION INC')
Company.create(name: 'ABOVENET COMMUNICATIONS INC')
Company.create(name: 'AMERICAN BUSINESS PRODS INC GA')
Company.create(name: 'AMBASSADOR BANK OF THE CMMWLTH')
Company.create(name: 'ACCENTIA BIOPHARMACEUTICALS INC')
Company.create(name: 'ATLANTIC PREMIUM BRANDS LTD')
Company.create(name: 'ARBOR REALTY TRUST INC')
Company.create(name: 'AMERICAN CRAFT BREWING INTL')
Company.create(name: 'A B R INFORMATION SERVICES INC')
Company.create(name: 'ABLE LABORATORIES INC')
StockSymbol.create(name: 'a.1', trading_name: 'a', company_id: 1)
StockSymbol.create(name: 'aab', trading_name: 'aab', company_id: 1)
StockSymbol.create(name: 'a', trading_name: 'a', company_id: 2)
StockSymbol.create(name: 'aa', trading_name: 'aa', company_id: 3)
StockSymbol.create(name: 'aaa', trading_name: 'aaa', company_id: 4)
StockSymbol.create(name: 'aaab', trading_name: 'aaab', company_id: 5)
StockSymbol.create(name: 'aabc', trading_name: 'aabc', company_id: 6)
StockSymbol.create(name: 'aac.1', trading_name: 'aac', company_id: 7)
StockSymbol.create(name: 'aac.2', trading_name: 'aac', company_id: 8)
StockSymbol.create(name: 'aacb', trading_name: 'aacb', company_id: 9)
StockSymbol.create(name: 'aacc', trading_name: 'aacc', company_id: 10)
StockSymbol.create(name: 'aace', trading_name: 'aace', company_id: 11)
StockSymbol.create(name: 'aadr', trading_name: 'aadr', company_id: 12)
StockSymbol.create(name: 'accu', trading_name: 'accu', company_id: 12)
StockSymbol.create(name: 'agls', trading_name: 'agls', company_id: 12)
StockSymbol.create(name: 'dbiz', trading_name: 'dbiz', company_id: 12)
StockSymbol.create(name: 'dent', trading_name: 'dent', company_id: 12)
StockSymbol.create(name: 'fwdb', trading_name: 'fwdb', company_id: 12)
StockSymbol.create(name: 'fwdd', trading_name: 'fwdd', company_id: 12)
StockSymbol.create(name: 'fwdi', trading_name: 'fwdi', company_id: 12)
StockSymbol.create(name: 'give', trading_name: 'give', company_id: 12)
StockSymbol.create(name: 'gtaa', trading_name: 'gtaa', company_id: 12)
StockSymbol.create(name: 'hdge', trading_name: 'hdge', company_id: 12)
StockSymbol.create(name: 'hyld', trading_name: 'hyld', company_id: 12)
StockSymbol.create(name: 'math', trading_name: 'math', company_id: 12)
StockSymbol.create(name: 'qeh', trading_name: 'qeh', company_id: 12)
StockSymbol.create(name: 'epro', trading_name: 'epro', company_id: 12)
StockSymbol.create(name: 'ssam', trading_name: 'ssam', company_id: 12)
StockSymbol.create(name: 'ttfs', trading_name: 'ttfs', company_id: 12)
StockSymbol.create(name: 'vega', trading_name: 'vega', company_id: 12)
StockSymbol.create(name: 'aadv', trading_name: 'aadv', company_id: 13)
StockSymbol.create(name: 'aaf', trading_name: 'aaf', company_id: 14)
StockSymbol.create(name: 'aafg', trading_name: 'aafg', company_id: 15)
StockSymbol.create(name: 'aagiy', trading_name: 'aagiy', company_id: 16)
StockSymbol.create(name: 'aah', trading_name: 'aah', company_id: 17)
StockSymbol.create(name: 'aai.1', trading_name: 'aai', company_id: 18)
StockSymbol.create(name: 'aai', trading_name: 'aai', company_id: 19)
StockSymbol.create(name: 'aaii', trading_name: 'aaii', company_id: 20)
StockSymbol.create(name: 'aaiie', trading_name: 'aaiie', company_id: 21)
StockSymbol.create(name: 'aait', trading_name: 'aait', company_id: 22)
StockSymbol.create(name: 'aala', trading_name: 'aala', company_id: 23)
StockSymbol.create(name: 'aam', trading_name: 'aam', company_id: 24)
StockSymbol.create(name: 'aame', trading_name: 'aame', company_id: 25)
StockSymbol.create(name: 'aan.1', trading_name: 'aan', company_id: 26)
StockSymbol.create(name: 'aan', trading_name: 'aan', company_id: 26)
StockSymbol.create(name: 'aanb', trading_name: 'aanb', company_id: 27)
StockSymbol.create(name: 'aaon', trading_name: 'aaon', company_id: 28)
StockSymbol.create(name: 'aap.1', trading_name: 'aap', company_id: 29)
StockSymbol.create(name: 'aap', trading_name: 'aap', company_id: 30)
StockSymbol.create(name: 'aapl', trading_name: 'aapl', company_id: 31)
StockSymbol.create(name: 'aasi', trading_name: 'aasi', company_id: 32)
StockSymbol.create(name: 'aasp', trading_name: 'aasp', company_id: 33)
StockSymbol.create(name: 'aat.1', trading_name: 'aat', company_id: 34)
StockSymbol.create(name: 'aat', trading_name: 'aat', company_id: 35)
StockSymbol.create(name: 'aati.1', trading_name: 'aati', company_id: 36)
StockSymbol.create(name: 'aati', trading_name: 'aati', company_id: 37)
StockSymbol.create(name: 'aatt', trading_name: 'aatt', company_id: 38)
StockSymbol.create(name: 'aau', trading_name: 'aau', company_id: 39)
StockSymbol.create(name: 'aauk', trading_name: 'aauk', company_id: 40)
StockSymbol.create(name: 'aav.1', trading_name: 'aav', company_id: 41)
StockSymbol.create(name: 'aav', trading_name: 'aav', company_id: 42)
StockSymbol.create(name: 'aaww', trading_name: 'aaww', company_id: 43)
StockSymbol.create(name: 'cgo.1', trading_name: 'cgo', company_id: 43)
StockSymbol.create(name: 'aaxj', trading_name: 'aaxj', company_id: 44)
StockSymbol.create(name: 'acwi', trading_name: 'acwi', company_id: 44)
StockSymbol.create(name: 'acwx', trading_name: 'acwx', company_id: 44)
StockSymbol.create(name: 'agg', trading_name: 'agg', company_id: 44)
StockSymbol.create(name: 'agz', trading_name: 'agz', company_id: 44)
StockSymbol.create(name: 'aia', trading_name: 'aia', company_id: 44)
StockSymbol.create(name: 'alt', trading_name: 'alt', company_id: 44)
StockSymbol.create(name: 'amps', trading_name: 'amps', company_id: 44)
StockSymbol.create(name: 'aoa', trading_name: 'aoa', company_id: 44)
StockSymbol.create(name: 'aok', trading_name: 'aok', company_id: 44)
StockSymbol.create(name: 'aom', trading_name: 'aom', company_id: 44)
StockSymbol.create(name: 'aor', trading_name: 'aor', company_id: 44)
StockSymbol.create(name: 'axdi', trading_name: 'axdi', company_id: 44)
StockSymbol.create(name: 'axen', trading_name: 'axen', company_id: 44)
StockSymbol.create(name: 'axhe', trading_name: 'axhe', company_id: 44)
StockSymbol.create(name: 'axid', trading_name: 'axid', company_id: 44)
StockSymbol.create(name: 'axit', trading_name: 'axit', company_id: 44)
StockSymbol.create(name: 'axmt', trading_name: 'axmt', company_id: 44)
StockSymbol.create(name: 'axsl', trading_name: 'axsl', company_id: 44)
StockSymbol.create(name: 'axte', trading_name: 'axte', company_id: 44)
StockSymbol.create(name: 'axut', trading_name: 'axut', company_id: 44)
StockSymbol.create(name: 'cft', trading_name: 'cft', company_id: 44)
StockSymbol.create(name: 'ciu', trading_name: 'ciu', company_id: 44)
StockSymbol.create(name: 'cly', trading_name: 'cly', company_id: 44)
StockSymbol.create(name: 'cmbs', trading_name: 'cmbs', company_id: 44)
StockSymbol.create(name: 'cmf', trading_name: 'cmf', company_id: 44)
StockSymbol.create(name: 'csj', trading_name: 'csj', company_id: 44)
StockSymbol.create(name: 'dsi', trading_name: 'dsi', company_id: 44)
StockSymbol.create(name: 'dvy', trading_name: 'dvy', company_id: 44)
StockSymbol.create(name: 'ecns', trading_name: 'ecns', company_id: 44)
StockSymbol.create(name: 'eem', trading_name: 'eem', company_id: 44)
StockSymbol.create(name: 'efa', trading_name: 'efa', company_id: 44)
StockSymbol.create(name: 'efav', trading_name: 'efav', company_id: 44)
StockSymbol.create(name: 'efg', trading_name: 'efg', company_id: 44)
StockSymbol.create(name: 'efv', trading_name: 'efv', company_id: 44)
StockSymbol.create(name: 'eido', trading_name: 'eido', company_id: 44)
StockSymbol.create(name: 'eirl', trading_name: 'eirl', company_id: 44)
stock_symbol_1 = StockSymbol.find(2)
stock_symbol_2 = StockSymbol.find(50)
user_guest_1 = User.create!(name: 'guest', email: '')
portfolio_1 = Portfolio.create(user: user_guest_1, name: 'Crazy Eights')
portfolio_1.open_positions.new(stock_symbol: stock_symbol_1, quantity: 100, cost: 113.16, date_acquired: Date.new(2009,9, 1))
portfolio_1.open_positions.new(stock_symbol: stock_symbol_2, quantity: 250, cost:   3.16, date_acquired: Date.new(2010,2,15))
portfolio_1.save!
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20090812, open_price: 113.16, close_price: 114.24, high_price: 115.01, low_price: 112.11, trade_volume: 1341)
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20090912, open_price: 115.16, close_price: 116.24, high_price: 116.24, low_price: 114.11, trade_volume: 1141)
DailyTrade.create(stock_symbol: stock_symbol_1, trade_date: 20091012, open_price: 111.16, close_price: 114.24, high_price: 115.01, low_price: 112.11, trade_volume:  941)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100116, open_price:   3.16, close_price:   4.24, high_price:   5.01, low_price:   2.11, trade_volume: 1776)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100216, open_price:   5.16, close_price:   6.24, high_price:   5.01, low_price:   4.11, trade_volume: 1576)
DailyTrade.create(stock_symbol: stock_symbol_2, trade_date: 20100316, open_price:   3.16, close_price:   5.24, high_price:   6.01, low_price:   3.11, trade_volume: 1376)
